// @ts-nocheck
// Task 6 / touchpoint 4 (write-side) — emit AIF skill-context overrides for
// top-3 AIF skills (aif-fix, aif-implement, aif-architecture) per
// phase-4-research §4.6. Closes touchpoint 4 from aif-comparison.md §5
// in Phase 4 instead of deferring to Phase 11.

import { mkdirSync, writeFileSync } from 'node:fs';
import { resolve } from 'node:path';
import type { DetectionResult } from './types.ts';

export const TOP_SKILLS = ['aif-fix', 'aif-implement', 'aif-architecture'] as const;
export type TopSkill = (typeof TOP_SKILLS)[number];

function renderSkillContext(skill: TopSkill, result: DetectionResult): string {
  const fwName = result.framework.name ?? 'unknown';
  const fwMajor = result.framework.major ?? 'unknown';
  const fwVersion = result.framework.version ?? 'unknown';
  const lines = [
    `# ${skill} — project-level overrides`,
    '',
    '> Auto-generated by `@rules-as-tests/core/detector` (Phase 4, touchpoint 4 write-side).',
    '> Re-run `rules-as-tests-detect <root> --emit-skill-context=<dir>` to refresh.',
    '',
    '## Stack',
    '',
    `- **Stack:** ${result.stack}`,
    `- **Framework:** ${fwName}${fwName !== 'unknown' ? ` ${fwVersion}` : ''} (major: ${fwMajor})`,
    `- **Runtime:** ${result.runtime.name}${result.runtime.major !== null ? ` ${result.runtime.major}` : ''}`,
    `- **Detection source:** \`${result.source || '(none)'}\``,
    `- **Confidence:** ${result.confidence} (severity: ${result.severity}, weight: ${result.weight})`,
    '',
    '## Notes',
    '',
    skill === 'aif-fix'
      ? '- Fix-skill should target the framework above; skip framework-specific patterns when stack is `ts-server`.'
      : skill === 'aif-implement'
        ? '- Implementation skill should respect the detected major version when picking idioms (e.g. Next 15 vs 16, React 18 vs 19).'
        : '- Architecture skill should anchor decisions to the source-of-truth file listed above; do not re-derive from package.json if a higher-priority AIF artifact is present.',
    '',
  ];
  return lines.join('\n');
}

export function writeSkillContext(outDir: string, result: DetectionResult): string[] {
  const written: string[] = [];
  for (const skill of TOP_SKILLS) {
    const dir = resolve(outDir, skill);
    mkdirSync(dir, { recursive: true });
    const file = resolve(dir, 'SKILL.md');
    writeFileSync(file, renderSkillContext(skill, result));
    written.push(file);
  }
  return written;
}
