#!/usr/bin/env bash
# f17 — live-signal Check 3 Arm (ii): planted violation FLAGGED by the SHIPPED lint rule.
#
# SCOPE NOTE — this is the NET-NEW arm the existing tests do NOT cover:
#   - gh-535-rule-enforced.test.sh: asserts R2 is PRESENT in resolved eslint config (Arm i)
#   - f3-f7-rule-globs.test.sh: asserts globs REACH boundary files (Arm i complement)
#   f3-f7 SCOPE NOTE: "A full `eslint .` run needs the consumer toolchain; out of this light harness."
#
# THIS CHECK fills that gap: install a consumer via install.sh → load the SHIPPED
# eslint-rules-local/no-unsafe-zod-parse.ts (NOT a reimplementation) through the
# generated barrel (index.ts) → use ESLint's Linter API to run the rule → assert
# the rule's messageId 'useSafeParse' fires on a planted .parse() call.
#
# Goes RED if the shipped rule is:
#   - DELETED (install.sh omits it; barrel missing export → linter.verify crashes)
#   - BROKEN (wrong selector / logic → violation not flagged)
#   - MIS-SELECTORED (AST selector doesn't match .parse() calls → exit 0, no message)
#   - BARREL BROKEN (index.ts barrel generation skipped/wrong → import fails)
#
# APPROACH — two arms:
#   Arm (i) form-check: install.sh copies rule + generates barrel.
#     Goes RED if eslint-rules-local/no-unsafe-zod-parse.ts or index.ts absent post-install.
#     PAIRED-NEGATIVE: deleting source rule → copy step omits it → Arm (i) RED.
#
#   Arm (ii) runtime signal (via tsx + ESLint Linter API):
#     Writes tiny TypeScript test scripts inside the consumer (where node_modules is
#     symlinked from packages/core), runs them via tsx which handles .ts imports, uses
#     the ESLint Linter class to invoke the shipped rule against test strings.
#     If tsx or eslint binary absent → SKIP with logged reason (never silently pass).
#     PAIRED-NEGATIVE: audit:exempt comment → rule skips line → no violation.
#
# WHY NOT eslint CLI with eslint.config.mjs: the shipped config uses
# tseslint.configs.strictTypeChecked which requires a tsconfig.json, and importing
# .ts config files via node --import tsx/esm triggers ERR_REQUIRE_CYCLE_MODULE in
# ESLint v9's CJS-then-ESM config loading path. The Linter API approach avoids both
# issues and directly tests the shipped rule logic.
#
# REQUIRES: tsx binary (hoisted by npm workspace install) + eslint (packages/core install).
set -uo pipefail
REPO_ROOT=$(git -C "$(dirname "$0")" rev-parse --show-toplevel)
PASS=0; FAIL=0
ok()  { PASS=$((PASS+1)); echo "  ✓ $1"; }
bad() { FAIL=$((FAIL+1)); echo "  ✗ $1"; }
skip(){ echo "  · $1"; }

# ── Arm (i) form-check: install.sh copies rule + generates barrel ──────────────
E=$(mktemp -d)
printf '{"name":"f17-test","version":"0.0.0"}\n' > "$E/package.json"
(cd "$E" && git init -q && bash "$REPO_ROOT/install.sh" ts-server --force </dev/null) \
  >"$E/.install.log" 2>&1
install_rc=$?

if [ "$install_rc" -ne 0 ]; then
  bad "Check3: install.sh non-zero rc=$install_rc (tail: $(tail -3 "$E/.install.log" | tr '\n' '|'))"
  echo ""; echo "PASS=$PASS FAIL=$FAIL"; exit 1
fi

if [ -f "$E/eslint-rules-local/no-unsafe-zod-parse.ts" ]; then
  ok "Check3 Arm(i): eslint-rules-local/no-unsafe-zod-parse.ts present (shipped rule copied by install.sh)"
else
  bad "Check3 Arm(i): eslint-rules-local/no-unsafe-zod-parse.ts MISSING — install.sh did not copy shipped rule (RED: rule deleted or copy step broken)"
fi

if [ -f "$E/eslint-rules-local/index.mjs" ]; then
  ok "Check3 Arm(i): eslint-rules-local/index.mjs present (compiled ESM barrel generated by install.sh)"
else
  bad "Check3 Arm(i): eslint-rules-local/index.mjs MISSING — barrel generation broken (RED: rule unreachable from eslint.config.mjs; Node 22 fix S2)"
fi

# ── Arm (iii) RAW-CHANNEL load (premise-aware, S1 #744 / fix #752) ─────────────
# The barrel + its sibling rule files must load via a RAW `node` import — NO tsx, NO
# NODE_OPTIONS — the exact path that CRASHED with the old `.ts` barrel
# (`ERR_UNKNOWN_FILE_EXTENSION ".ts"`) on a Node without native type-stripping: Node 20.x
# (the consumer's own .nvmrc = 20.19.0) and Node 22.0–22.17. This is the REAL consumer
# exposure — raw pre-commit/lint-staged + manual `npx eslint` — distinct from Arm (ii)'s
# tsx Linter-API path which always worked and so never proved the fix (S1 #744). Under the
# CI Node 20+22 matrix (audit-self.yml f17-node-compat) this arm is the honest "green stops
# lying" gate. Variant A (#752): rule `.mjs` are PRE-COMPILED + shipped, so this loads with
# no tsc — directly disproving #745's compile-at-install green-lie.
raw_out=$(cd "$E" && node --input-type=module -e \
  "import('./eslint-rules-local/index.mjs').then(m => { const ok = m && m.default && m.default.rules && Object.keys(m.default.rules).length > 0; process.exit(ok ? 0 : 3); }).catch(e => { console.error(String((e && e.message) || (e && e.code) || e)); process.exit(4); })" 2>&1)
raw_rc=$?
if [ "$raw_rc" -eq 0 ]; then
  ok "Check3 Arm(iii): barrel + rules load via RAW node import — NO tsx — on Node $(node -p 'process.versions.node') (raw pre-commit/npx-eslint channel; #752 fix proof)"
elif echo "$raw_out" | grep -qiE "cannot find package|cannot find package 'eslint'|ERR_MODULE_NOT_FOUND.*@typescript-eslint"; then
  skip "Check3 Arm(iii) SKIP — runtime dep (@typescript-eslint/utils / eslint) not resolvable in this harness ($(echo "$raw_out" | head -1 | tr -d '\n')); the .mjs barrel itself is present (Arm i). CI Node-matrix job resolves deps."
elif echo "$raw_out" | grep -qiE "unknown file extension|cannot find module '\./"; then
  bad "Check3 Arm(iii): RAW barrel load FAILED on Node $(node -p 'process.versions.node') ($(echo "$raw_out" | head -1 | tr -d '\n')) — the .ts-loader / missing-sibling-.mjs regression is NOT fixed on the raw channel (#752 / S1 class)"
else
  skip "Check3 Arm(iii) SKIP — inconclusive raw-load (rc=$raw_rc; $(echo "$raw_out" | head -1 | tr -d '\n'))"
fi

# ── Arm (ii) runtime signal: tsx + ESLint Linter API ─────────────────────────
# Locate tsx binary (hoisted by root workspace npm install; also in packages/core)
TSX_BIN=""
for _t in \
  "$REPO_ROOT/packages/core/node_modules/.bin/tsx" \
  "$REPO_ROOT/node_modules/.bin/tsx" \
  "/app/node_modules/.bin/tsx"; do
  [ -x "$_t" ] && TSX_BIN="$_t" && break
done

# Locate eslint binary (needed to find the packages/core node_modules tree for symlink)
ESLINT_BIN=""
for _e in \
  "$REPO_ROOT/packages/core/node_modules/.bin/eslint" \
  "$REPO_ROOT/node_modules/.bin/eslint" \
  "/app/node_modules/.bin/eslint"; do
  [ -x "$_e" ] && ESLINT_BIN="$_e" && break
done

if [ -z "$TSX_BIN" ] || [ -z "$ESLINT_BIN" ]; then
  skip "Check3 Arm(ii) SKIP — tsx ($([ -n "$TSX_BIN" ] && echo found || echo missing)) or eslint ($([ -n "$ESLINT_BIN" ] && echo found || echo missing)) binary not available; needs npm install --prefix packages/core + npm install. Arm(i) form-check above confirms rule file + barrel exist on disk."
  echo ""; echo "PASS=$PASS FAIL=$FAIL"; [ "$FAIL" -eq 0 ]; exit $?
fi
echo "  · using tsx: $TSX_BIN"
echo "  · using eslint node_modules: $(dirname "$(dirname "$ESLINT_BIN")")"

# Symlink packages/core/node_modules into consumer so the shipped rule's TypeScript
# imports (@typescript-eslint/utils) resolve when tsx loads the barrel.
NM_SRC="$(dirname "$(dirname "$ESLINT_BIN")")"   # e.g. /app/node_modules
if [ ! -e "$E/node_modules" ]; then
  ln -s "$NM_SRC" "$E/node_modules"
fi

# Write tiny TypeScript test scripts inside the consumer (resolves imports from
# consumer's node_modules symlink). Using ESLint's Linter API rather than CLI to
# avoid the ESM/CJS cycle issue in eslint v9's --import tsx/esm config loading.

# POSITIVE arm script: violation → rule fires → exit 0
# Note: no configType option — works with both ESLint v9 (flat default) and v10 (flat only)
cat > "$E/f17-pos.mts" << 'SCRIPT'
import { Linter } from 'eslint';
import { default as plugin } from './eslint-rules-local/index.mjs';
const linter = new Linter();
const cfg = [{ plugins: { rat: plugin }, rules: { 'rat/no-unsafe-zod-parse': 'error' }, languageOptions: { ecmaVersion: 2022 } }];
const msgs = linter.verify("const bodySchema={parse:x=>x};const r=bodySchema.parse('x');", cfg, { filename: 'test.js' });
process.exit(msgs.some(m => m.ruleId === 'rat/no-unsafe-zod-parse') ? 0 : 1);
SCRIPT

# NEGATIVE arm script: audit:exempt → rule skips → exit 0
cat > "$E/f17-neg.mts" << 'SCRIPT'
import { Linter } from 'eslint';
import { default as plugin } from './eslint-rules-local/index.mjs';
const linter = new Linter();
const cfg = [{ plugins: { rat: plugin }, rules: { 'rat/no-unsafe-zod-parse': 'error' }, languageOptions: { ecmaVersion: 2022 } }];
const msgs = linter.verify("const bodySchema={parse:x=>x};const r=bodySchema.parse('x'); // audit:exempt", cfg, { filename: 'test.js' });
process.exit(msgs.some(m => m.ruleId === 'rat/no-unsafe-zod-parse') ? 1 : 0);
SCRIPT

# ── POSITIVE: violation → shipped rule fires ──────────────────────────────────
pos_out=$(cd "$E" && "$TSX_BIN" f17-pos.mts 2>&1)
pos_rc=$?
if [ "$pos_rc" -eq 0 ]; then
  ok "Check3 Arm(ii): planted .parse() violation FLAGGED by shipped eslint-rules-local/no-unsafe-zod-parse.ts (live signal; NOT a reimplementation)"
elif echo "$pos_out" | grep -qiE 'cannot find module|cannot find package|ERR_MODULE_NOT_FOUND|ERR_PACKAGE_PATH'; then
  skip "Check3 Arm(ii) SKIP — tsx failed to load module (infrastructure: $(echo "$pos_out" | grep -iE 'cannot find|ERR_MODULE' | head -1 | tr -d '\n')). Rule file + barrel confirmed present by Arm(i)."
else
  bad "Check3 Arm(ii): shipped rule did NOT flag planted violation (rule deleted/broken/mis-selectored; rc=$pos_rc; out=$(echo "$pos_out" | head -3 | tr '\n' '|'))"
fi

# ── PAIRED-NEGATIVE: audit:exempt → rule skips the line ─────────────────────
neg_out=$(cd "$E" && "$TSX_BIN" f17-neg.mts 2>&1)
neg_rc=$?
if echo "$neg_out" | grep -qiE 'cannot find module|cannot find package|ERR_MODULE_NOT_FOUND|ERR_PACKAGE_PATH'; then
  skip "Check3 Arm(ii) neg SKIP — tsx module load failed (same infrastructure issue as positive arm)"
elif [ "$neg_rc" -eq 0 ]; then
  ok "Check3 Arm(ii) neg: audit:exempt → rule skips line (non-vacuous: shipped rule is live + exempt path works)"
else
  bad "Check3 Arm(ii) neg: exempt line still flagged OR error (rc=$neg_rc; out=$(echo "$neg_out" | head -3 | tr '\n' '|'))"
fi

echo ""; echo "PASS=$PASS FAIL=$FAIL"; [ "$FAIL" -eq 0 ]
