#!/usr/bin/env bash
# t6 — synth-wire planted-violation test (T-GIW-A falsification).
#
# SCOPE: Proves that the synthesizer-driven rules-as-tests slice is APPLIED in the
# consumer's resolved config (not just present in the barrel/config file).  Falsifies
# T-GIW-A: «emitted files exist / output equals preset, therefore done» — equality
# with the gold preset is the oracle pass, NOT proof of enforcement.
#
# Gates tested:
#   A. synth-wire ran: 99-finalize.sh called synth-and-wire.ts and it reported
#      idempotent-or-wired on the root eslint.config.mjs.
#   B. Rule PRESENT: eslint-rules-local/ has both `restricted-syntax-audit-exempt.ts`
#      and `no-server-imports-in-client.ts` (the two rule files backing synthesized rules).
#      (T-GIW-A arm: rule file + barrel)
#   C. Rule WIRED + APPLIED: reads the install-produced $E/eslint.config.mjs to confirm
#      the synthesizer-driven rules-as-tests slice is wired into the resolved consumer
#      config (not just present as rule files on disk).
#      C0 — config-level grep: rules-as-tests/restricted-syntax-audit-exempt and
#           no-server-imports-in-client present in installed eslint.config.mjs.
#      C-cfg — eslint --print-config <boundary-file>: resolved config includes rules-as-tests
#           rule (best-effort; SKIP on missing plugins in test env).
#      C1 — R20 selector EXTRACTED from installed eslint.config.mjs (not hardcoded) fires
#           on async export without 'use server' directive.
#      C2 — no-server-imports-in-client (confirmed wired by C0) fires on 'use client'
#           file importing 'fs'.
#   D. Paired-negative: rule skips when 'use server' / non-client file.
#
# T-GIW-A falsification: would fail if synth-and-wire.ts wired nothing into eslint.config.mjs
#   — C0 grep would not find the rule, and C1's tsx script exits 3 (config-missing) before
#   ever reaching the Linter API.
#
# Model: tests/install-sh/f17-lint-rules-planted-violation.test.sh
# Prior-art: prior-art-evaluations.md#114 (guard-liveness), #120 (install wires R2 by reading repo)
set -uo pipefail
REPO_ROOT=$(git -C "$(dirname "$0")" rev-parse --show-toplevel)
PASS=0; FAIL=0
ok()   { PASS=$((PASS+1)); echo "  ✓ $1"; }
bad()  { FAIL=$((FAIL+1)); echo "  ✗ $1"; }
skip() { echo "  · $1"; }

# ── Arm A/B — install react-next + confirm synth-wire ran ────────────────────
E=$(mktemp -d)
printf '{"name":"t6-synth-wire-test","version":"0.0.0"}\n' > "$E/package.json"
# Capture install.sh output to check for synth-wire log line
(cd "$E" && git init -q && bash "$REPO_ROOT/install.sh" react-next --force </dev/null) \
  >"$E/.install.log" 2>&1
install_rc=$?

if [ "$install_rc" -ne 0 ]; then
  bad "t6 A: install.sh react-next non-zero rc=$install_rc (tail: $(tail -3 "$E/.install.log" | tr '\n' '|'))"
  echo ""; echo "PASS=$PASS FAIL=$FAIL"; exit 1
fi

# A: synth-wire reported idempotent or wired (the key log line)
if grep -q 'synth-wire.*confirmed\|synth-wire.*wired\|synth-wire.*idempotent' "$E/.install.log"; then
  ok "t6 A: synth-and-wire.ts ran and reported status for react-next stack"
elif grep -q 'synth-wire.*skipped\|synth-wire.*not found' "$E/.install.log"; then
  skip "t6 A: synth-and-wire.ts skipped (script not found or node absent; Arm B/C still verifies)"
else
  bad "t6 A: synth-wire log line not found in install output (install.sh may not call synth-and-wire.ts)"
fi

# B: Rule files present in consumer barrel
if [ -f "$E/eslint-rules-local/restricted-syntax-audit-exempt.ts" ]; then
  ok "t6 B1: eslint-rules-local/restricted-syntax-audit-exempt.ts present (core rule for R14/R20 wrapper)"
else
  bad "t6 B1: eslint-rules-local/restricted-syntax-audit-exempt.ts MISSING — install.sh did not copy core rule"
fi

if [ -f "$E/eslint-rules-local/no-server-imports-in-client.ts" ]; then
  ok "t6 B2: eslint-rules-local/no-server-imports-in-client.ts present (R12 rule for react-next)"
else
  bad "t6 B2: eslint-rules-local/no-server-imports-in-client.ts MISSING — install.sh did not copy preset rule"
fi

if [ -f "$E/eslint-rules-local/index.mjs" ]; then
  ok "t6 B3: eslint-rules-local/index.mjs present (barrel generated by install.sh)"
else
  bad "t6 B3: eslint-rules-local/index.mjs MISSING — barrel generation broken"
fi

# ── Arm C — T-GIW-A: rule wired into RESOLVED consumer config ─────────────────
# Reads the install-produced $E/eslint.config.mjs to confirm the rules-as-tests slice
# is present in the resolved consumer config.  Would fail if synth-and-wire.ts wired
# nothing into eslint.config.mjs (T-GIW-A gate).

# C0: config-level grep — confirms rules ARE wired into the installed eslint.config.mjs
if [ ! -f "$E/eslint.config.mjs" ]; then
  bad "t6 C0: eslint.config.mjs not found in consumer dir — install.sh did not copy ESLint config"
elif grep -q "rules-as-tests/restricted-syntax-audit-exempt" "$E/eslint.config.mjs"; then
  ok "t6 C0: eslint.config.mjs contains rules-as-tests/restricted-syntax-audit-exempt (synthesizer-driven rule wired into resolved consumer config — T-GIW-A config gate)"
else
  bad "t6 C0: eslint.config.mjs does NOT contain rules-as-tests/restricted-syntax-audit-exempt — synth-and-wire did not wire the rule into the installed consumer config (T-GIW-A FAIL)"
fi

if [ -f "$E/eslint.config.mjs" ] && grep -q "rules-as-tests/no-server-imports-in-client" "$E/eslint.config.mjs"; then
  ok "t6 C0b: eslint.config.mjs contains rules-as-tests/no-server-imports-in-client (R12 rule wired into resolved config)"
else
  bad "t6 C0b: eslint.config.mjs does NOT contain rules-as-tests/no-server-imports-in-client"
fi

# ── locate tsx + eslint binaries ─────────────────────────────────────────────
TSX_BIN=""
for _t in \
  "$REPO_ROOT/packages/core/node_modules/.bin/tsx" \
  "$REPO_ROOT/node_modules/.bin/tsx" \
  "/app/node_modules/.bin/tsx"; do
  [ -x "$_t" ] && TSX_BIN="$_t" && break
done

ESLINT_BIN=""
for _e in \
  "$REPO_ROOT/packages/core/node_modules/.bin/eslint" \
  "$REPO_ROOT/node_modules/.bin/eslint" \
  "/app/node_modules/.bin/eslint"; do
  [ -x "$_e" ] && ESLINT_BIN="$_e" && break
done

if [ -z "$TSX_BIN" ] || [ -z "$ESLINT_BIN" ]; then
  skip "t6 C1/C2/C-cfg SKIP — tsx ($([ -n "$TSX_BIN" ] && echo found || echo missing)) or eslint ($([ -n "$ESLINT_BIN" ] && echo found || echo missing)) not available; Arm C0 config-level check above confirms rules wired into eslint.config.mjs."
  echo ""; echo "PASS=$PASS FAIL=$FAIL"; [ "$FAIL" -eq 0 ]; exit $?
fi
echo "  · using tsx: $TSX_BIN"

NM_SRC="$(dirname "$(dirname "$ESLINT_BIN")")"
if [ ! -e "$E/node_modules" ]; then
  ln -s "$NM_SRC" "$E/node_modules"
fi

# ── C-cfg: eslint --print-config on resolved consumer config (best-effort) ────
# Attempts to verify the rule via the resolved config for a boundary file.
# SKIP gracefully if config load fails due to missing plugin packages in test env.
mkdir -p "$E/app/actions"
printf 'export async function action() {}\n' > "$E/app/actions/t6-probe.ts"
cfg_out=$(cd "$E" && "$ESLINT_BIN" --print-config app/actions/t6-probe.ts 2>&1)
cfg_rc=$?
if [ "$cfg_rc" -eq 0 ] && echo "$cfg_out" | grep -q 'restricted-syntax-audit-exempt'; then
  ok "t6 C-cfg: eslint --print-config confirms rules-as-tests/restricted-syntax-audit-exempt in resolved config for boundary file (app/actions/*.ts)"
elif echo "$cfg_out" | grep -qiE 'ERR_MODULE_NOT_FOUND|Cannot find package'; then
  skip "t6 C-cfg SKIP — eslint --print-config could not load full config (missing plugin packages in test env; C0 config-level grep confirms rule IS in eslint.config.mjs)"
else
  skip "t6 C-cfg SKIP — eslint --print-config rc=$cfg_rc (out=$(echo "$cfg_out" | head -1 | tr -d '\n'))"
fi

# ── C1 positive: R20 selector EXTRACTED from installed eslint.config.mjs fires ─
# Reads selector from the INSTALLED config (not hardcoded) — test goes RED if
# eslint.config.mjs does not contain the rule (process.exit(3) = config-missing).
cat > "$E/t6-c1-pos.mts" << 'SCRIPT'
import { readFileSync } from 'fs';
import { Linter } from 'eslint';
import { default as plugin } from './eslint-rules-local/index.mjs';

// Read the INSTALLED consumer config (source of truth — not a hand-written inline config)
const configText = readFileSync('./eslint.config.mjs', 'utf8');

// Assert rule is wired into installed config (exits 3 if synth-and-wire wired nothing)
if (!configText.includes("rules-as-tests/restricted-syntax-audit-exempt")) {
  process.stderr.write("FAIL[config-missing]: rules-as-tests/restricted-syntax-audit-exempt not found in installed eslint.config.mjs\n");
  process.exit(3);
}

// Extract R20 selector FROM the installed config text (not hardcoded — unique signature:
// double-quoted string starting with "Program:not(Program:has(")
const r20Matches = [...configText.matchAll(/"(Program:not\(Program:has\([^"]+)"/g)];
const r20Selector = r20Matches[0]?.[1];
if (!r20Selector) {
  process.stderr.write("FAIL[selector-missing]: R20 selector not found in installed eslint.config.mjs\n");
  process.exit(3);
}

// Run Linter with EXTRACTED selector + installed barrel; positive arm: violation MUST fire
const linter = new Linter();
const cfg = [{
  plugins: { rat: plugin },
  rules: { 'rat/restricted-syntax-audit-exempt': ['error', { selector: r20Selector, message: 'R20' }] },
  languageOptions: { ecmaVersion: 2022 },
}];
const code = "export async function action() { return 1; }"; // no 'use server' → violation
// .js filename required — TypeScript-aware parser is not available in the Linter API context
const msgs = linter.verify(code, cfg, { filename: 'test-action.js' });
process.exit(msgs.some(m => m.ruleId === 'rat/restricted-syntax-audit-exempt') ? 0 : 1);
SCRIPT

# ── C1 negative: 'use server' directive → no violation ────────────────────────
cat > "$E/t6-c1-neg.mts" << 'SCRIPT'
import { readFileSync } from 'fs';
import { Linter } from 'eslint';
import { default as plugin } from './eslint-rules-local/index.mjs';

const configText = readFileSync('./eslint.config.mjs', 'utf8');
if (!configText.includes("rules-as-tests/restricted-syntax-audit-exempt")) {
  process.stderr.write("FAIL[config-missing]\n"); process.exit(3);
}
const r20Matches = [...configText.matchAll(/"(Program:not\(Program:has\([^"]+)"/g)];
const r20Selector = r20Matches[0]?.[1];
if (!r20Selector) { process.stderr.write("FAIL[selector-missing]\n"); process.exit(3); }

const linter = new Linter();
const cfg = [{
  plugins: { rat: plugin },
  rules: { 'rat/restricted-syntax-audit-exempt': ['error', { selector: r20Selector, message: 'R20' }] },
  languageOptions: { ecmaVersion: 2022 },
}];
const code = "'use server';\nexport async function action() { return 1; }"; // 'use server' present → no violation
const msgs = linter.verify(code, cfg, { filename: 'test-action.js' });
process.exit(msgs.some(m => m.ruleId === 'rat/restricted-syntax-audit-exempt') ? 1 : 0);
SCRIPT

# ── C2 positive: no-server-imports-in-client fires on 'use client' + import fs ─
# Rule config is static ('error'); wiring confirmed by C0b grep above.
cat > "$E/t6-c2-pos.mts" << 'SCRIPT'
import { readFileSync } from 'fs';
import { Linter } from 'eslint';
import { default as plugin } from './eslint-rules-local/index.mjs';

// Assert rule is wired into installed config (exits 3 if not)
const configText = readFileSync('./eslint.config.mjs', 'utf8');
if (!configText.includes("rules-as-tests/no-server-imports-in-client")) {
  process.stderr.write("FAIL[config-missing]: rules-as-tests/no-server-imports-in-client not found in installed eslint.config.mjs\n");
  process.exit(3);
}
const linter = new Linter();
const cfg = [{
  plugins: { rat: plugin },
  rules: { 'rat/no-server-imports-in-client': 'error' },
  languageOptions: { ecmaVersion: 2022, sourceType: 'module' },
}];
const code = "'use client';\nimport fs from 'fs';\nexport const x = 1;";
const msgs = linter.verify(code, cfg, { filename: 'test.js' });
process.exit(msgs.some(m => m.ruleId === 'rat/no-server-imports-in-client') ? 0 : 1);
SCRIPT

# ── C2 negative: non-client file → no violation ───────────────────────────────
cat > "$E/t6-c2-neg.mts" << 'SCRIPT'
import { readFileSync } from 'fs';
import { Linter } from 'eslint';
import { default as plugin } from './eslint-rules-local/index.mjs';

const configText = readFileSync('./eslint.config.mjs', 'utf8');
if (!configText.includes("rules-as-tests/no-server-imports-in-client")) {
  process.stderr.write("FAIL[config-missing]\n"); process.exit(3);
}
const linter = new Linter();
const cfg = [{
  plugins: { rat: plugin },
  rules: { 'rat/no-server-imports-in-client': 'error' },
  languageOptions: { ecmaVersion: 2022, sourceType: 'module' },
}];
const code = "import fs from 'fs';\nexport const x = 1;"; // no 'use client' → server file, no violation
const msgs = linter.verify(code, cfg, { filename: 'test.js' });
process.exit(msgs.some(m => m.ruleId === 'rat/no-server-imports-in-client') ? 1 : 0);
SCRIPT

# Run C1 positive
c1p_out=$(cd "$E" && "$TSX_BIN" t6-c1-pos.mts 2>&1)
c1p_rc=$?
if echo "$c1p_out" | grep -qiE 'cannot find module|ERR_MODULE_NOT_FOUND|ERR_PACKAGE_PATH'; then
  skip "t6 C1 pos SKIP — module load failed ($(echo "$c1p_out" | grep -iE 'cannot find|ERR_' | head -1 | tr -d '\n'))"
elif [ "$c1p_rc" -eq 3 ]; then
  bad "t6 C1 pos: R20 rule NOT FOUND in installed eslint.config.mjs — synth-and-wire did not wire it (T-GIW-A FAIL; detail=$(echo "$c1p_out" | head -1 | tr -d '\n'))"
elif [ "$c1p_rc" -eq 0 ]; then
  ok "t6 C1 pos: R20 selector (read from installed eslint.config.mjs, not hardcoded) FIRED on async export without 'use server' (T-GIW-A RED run against installed config)"
else
  bad "t6 C1 pos: R20 selector did NOT fire — rule not applied (rc=$c1p_rc; out=$(echo "$c1p_out" | head -3 | tr '\n' '|'))"
fi

# Run C1 negative
c1n_out=$(cd "$E" && "$TSX_BIN" t6-c1-neg.mts 2>&1)
c1n_rc=$?
if echo "$c1n_out" | grep -qiE 'cannot find module|ERR_MODULE_NOT_FOUND|ERR_PACKAGE_PATH'; then
  skip "t6 C1 neg SKIP — module load failed (same infrastructure issue)"
elif [ "$c1n_rc" -eq 3 ]; then
  bad "t6 C1 neg: config-missing error (detail=$(echo "$c1n_out" | head -1 | tr -d '\n'))"
elif [ "$c1n_rc" -eq 0 ]; then
  ok "t6 C1 neg: 'use server' present → R20 selector does NOT fire (paired-negative green)"
else
  bad "t6 C1 neg: 'use server' file still flagged OR error (rc=$c1n_rc)"
fi

# Run C2 positive
c2p_out=$(cd "$E" && "$TSX_BIN" t6-c2-pos.mts 2>&1)
c2p_rc=$?
if echo "$c2p_out" | grep -qiE 'cannot find module|ERR_MODULE_NOT_FOUND|ERR_PACKAGE_PATH'; then
  skip "t6 C2 pos SKIP — module load failed"
elif [ "$c2p_rc" -eq 3 ]; then
  bad "t6 C2 pos: config-missing — no-server-imports-in-client not found in installed eslint.config.mjs (detail=$(echo "$c2p_out" | head -1 | tr -d '\n'))"
elif [ "$c2p_rc" -eq 0 ]; then
  ok "t6 C2 pos: no-server-imports-in-client FIRED on 'use client' file importing 'fs' (rule wired into installed config and applied)"
else
  bad "t6 C2 pos: no-server-imports-in-client did NOT fire — rule not applied (rc=$c2p_rc; out=$(echo "$c2p_out" | head -3 | tr '\n' '|'))"
fi

# Run C2 negative
c2n_out=$(cd "$E" && "$TSX_BIN" t6-c2-neg.mts 2>&1)
c2n_rc=$?
if echo "$c2n_out" | grep -qiE 'cannot find module|ERR_MODULE_NOT_FOUND|ERR_PACKAGE_PATH'; then
  skip "t6 C2 neg SKIP — module load failed"
elif [ "$c2n_rc" -eq 3 ]; then
  bad "t6 C2 neg: config-missing error"
elif [ "$c2n_rc" -eq 0 ]; then
  ok "t6 C2 neg: server file (no 'use client') → no-server-imports-in-client does NOT fire (paired-negative green)"
else
  bad "t6 C2 neg: server file still flagged OR error (rc=$c2n_rc)"
fi

echo ""; echo "PASS=$PASS FAIL=$FAIL"; [ "$FAIL" -eq 0 ]
