/**
 * Principle 4 — No tautology
 *
 * Source: ai-traps.md §3 ("Tautological tests — expect(result).toBeDefined() for typed values")
 *         + overview.md Layer 3 anti-pattern ("Expected value generated by running the code →
 *         tautology farm") + self-testing-docs.md ("Probe без negative test не считается
 *         реализованным")
 *
 * Manifest field checked: Tautology in the manifest itself takes the form of:
 *   1. policy field containing only tautological statements (restates the title without adding
 *      enforcement information) — detectable as policy that is suspiciously short or
 *      identical to title.
 *   2. examples where bad and good are identical (covered in Principle 2, cross-check here).
 *   3. check.command / check.rule being a trivially no-op value (e.g., "true" or "echo OK").
 *
 * This test is also the meta-level application of Guardrail 2: the mutation tests here
 * verify that THIS meta-test is itself not tautological.
 *
 * Phase 2 scope: structural tautology detection in manifest fields.
 * Runtime tautology (whether an ESLint rule's AST assertion is actually non-trivial) → Phase 5.
 */
import { describe, it, expect } from 'vitest';
import { readFileSync } from 'node:fs';
import { resolve, dirname } from 'node:path';
import { fileURLToPath } from 'node:url';

const HERE = dirname(fileURLToPath(import.meta.url));
const ROOT = resolve(HERE, '../..');
const MANIFEST_PATH = resolve(ROOT, 'factory/rules-manifest.json');

interface RuleEntry {
  title: string;
  stack: string[];
  check: { type: string; command?: string; rule?: string; script?: string; rationale?: string };
  examples: { bad: string; good: string };
  policy?: string;
  [key: string]: unknown;
}

type Manifest = Record<string, RuleEntry>;

function loadManifest(): Manifest {
  return JSON.parse(readFileSync(MANIFEST_PATH, 'utf8')) as Manifest;
}

/**
 * No-op commands that would make a "command"-type check tautological.
 * These commands always succeed without performing real enforcement.
 */
const NOOP_COMMANDS = new Set(['true', 'echo ok', 'echo "ok"', "echo 'ok'", ':', 'exit 0']);

function assertPrinciple4(id: string, rule: RuleEntry): void {
  const check = rule.check;

  // Tautology check 1: command-type check that is trivially a no-op
  if (check.type === 'command' && check.command) {
    const cmd = check.command.trim().toLowerCase();
    if (NOOP_COMMANDS.has(cmd)) {
      throw new Error(
        `Rule ${id}: check.command is a no-op ("${check.command}"). ` +
          'A no-op command always succeeds and never enforces anything — structural tautology.',
      );
    }
  }

  // Tautology check 2: policy field (if present) must not be identical to title
  // A policy that just restates the title adds no enforcement information.
  if (rule.policy) {
    const normalizedPolicy = rule.policy.trim().toLowerCase();
    const normalizedTitle = rule.title.trim().toLowerCase();
    if (normalizedPolicy === normalizedTitle) {
      throw new Error(
        `Rule ${id}: policy field is identical to title — this is a tautology. ` +
          'Policy must describe enforcement details, not restate the title.',
      );
    }
  }

  // Tautology check 3: examples.bad === examples.good (structural tautology — same check as P2
  // but this is the "no-tautology" lens on the same data)
  if (rule.examples.bad.trim() === rule.examples.good.trim()) {
    throw new Error(
      `Rule ${id}: examples.bad === examples.good — tautological example pair. ` +
        'The bad example must show a genuinely different (violating) pattern.',
    );
  }
}

describe('Principle 4 — No tautology (structural: no-op checks, identical policy/title, identical examples)', () => {
  it('no rules have structural tautologies in manifest', () => {
    const manifest = loadManifest();
    const violations: string[] = [];

    for (const [id, rule] of Object.entries(manifest)) {
      try {
        assertPrinciple4(id, rule);
      } catch (err) {
        violations.push((err as Error).message);
      }
    }

    expect(violations, `Violations:\n${violations.join('\n')}`).toHaveLength(0);
  });

  it('mutation: command-type rule with no-op command causes assertion to fail (anti-tautology)', () => {
    const manifest = loadManifest();
    // Use a command-type rule for the mutation, or the first rule if none
    const commandEntry =
      Object.entries(manifest).find(([, r]) => r.check.type === 'command') ??
      (Object.entries(manifest)[0] as [string, RuleEntry]);
    const [id, rule] = commandEntry as [string, RuleEntry];

    const mutated: RuleEntry = {
      ...rule,
      check: { type: 'command', command: 'true' },
    };

    expect(() => assertPrinciple4(id, mutated)).toThrow(/no-op/);
  });

  it('mutation: rule with policy identical to title causes assertion to fail (anti-tautology)', () => {
    const manifest = loadManifest();
    const [firstId, firstRule] = Object.entries(manifest)[0] as [string, RuleEntry];

    const mutated: RuleEntry = {
      ...firstRule,
      policy: firstRule.title, // policy === title = tautology
    };

    expect(() => assertPrinciple4(firstId, mutated)).toThrow(/policy field is identical to title/);
  });

  it('mutation: rule with identical bad/good examples causes assertion to fail (anti-tautology)', () => {
    const manifest = loadManifest();
    const [firstId, firstRule] = Object.entries(manifest)[0] as [string, RuleEntry];

    const mutated: RuleEntry = {
      ...firstRule,
      examples: { bad: firstRule.examples.good, good: firstRule.examples.good },
    };

    expect(() => assertPrinciple4(firstId, mutated)).toThrow(/tautological example pair/);
  });
});
