/**
 * Principle 2 — Paired negative test for each rule
 *
 * Source: overview.md Layer 4 anti-pattern ("Expected value generated by running the code →
 *         tautology farm") + self-testing-docs.md ("Probe без negative test не считается
 *         реализованным") + ai-traps.md §3 (tautological tests)
 *
 * Manifest field checked: examples.bad (the "negative test" counterpart — shows what violates
 *   the rule). This is the structural proxy for "paired negative test": if examples.bad is
 *   absent or trivially empty, there is no documented violation scenario.
 *
 * Applicability: ALL rules (bad/good examples required by schema for all rule types).
 *
 * Note on deeper paired-negative-test infrastructure (running examples through ESLint):
 *   That requires Phase 5 runtime. Phase 2 covers structural presence only.
 *   See principles-as-tests.md §Known limitations.
 */
// @ts-nocheck

import { describe, it, expect } from 'vitest';
import { readFileSync } from 'node:fs';
import { resolve, dirname } from 'node:path';
import { fileURLToPath } from 'node:url';

const HERE = dirname(fileURLToPath(import.meta.url));
const MANIFEST_PATH = resolve(HERE, '../manifest/rules-manifest.json');
const SYNTH_FIXTURE_PATH = resolve(
  HERE,
  '../synthesizer/expected-fixture-synth.json',
);

interface RuleEntry {
  title: string;
  stack: string[];
  check: { type: string; [key: string]: unknown };
  examples: { bad: string; good: string };
  policy?: string;
  [key: string]: unknown;
}

interface SynthesizedRuleEntry extends RuleEntry {
  id: string;
  'negative-test'?: { input: string; 'expect-violation': string };
}

interface SynthFixture {
  rules: SynthesizedRuleEntry[];
}

type Manifest = Record<string, RuleEntry>;

function loadManifest(): Manifest {
  return JSON.parse(readFileSync(MANIFEST_PATH, 'utf8')) as Manifest;
}

function loadSynthFixture(): SynthFixture {
  return JSON.parse(readFileSync(SYNTH_FIXTURE_PATH, 'utf8')) as SynthFixture;
}

/** Minimum meaningful content length (not just whitespace or a comment marker) */
const MIN_EXAMPLE_LENGTH = 5;

function assertPrinciple2(id: string, rule: RuleEntry): void {
  const bad = rule.examples?.bad;
  const good = rule.examples?.good;

  if (!bad || bad.trim().length < MIN_EXAMPLE_LENGTH) {
    throw new Error(
      `Rule ${id}: examples.bad is absent or too short (< ${MIN_EXAMPLE_LENGTH} chars). ` +
        'A paired negative example is required to document what violates this rule.',
    );
  }

  if (!good || good.trim().length < MIN_EXAMPLE_LENGTH) {
    throw new Error(
      `Rule ${id}: examples.good is absent or too short (< ${MIN_EXAMPLE_LENGTH} chars). ` +
        'A paired positive example is required to document what satisfies this rule.',
    );
  }

  // The bad and good examples must differ — identical examples = tautology
  if (bad.trim() === good.trim()) {
    throw new Error(
      `Rule ${id}: examples.bad and examples.good are identical — this is a tautology. ` +
        'The negative example must show a different (violating) pattern from the positive.',
    );
  }
}

describe('Principle 2 — Paired negative test (examples.bad + examples.good)', () => {
  it('all rules have non-trivial paired bad/good examples', () => {
    const manifest = loadManifest();
    const violations: string[] = [];

    for (const [id, rule] of Object.entries(manifest)) {
      try {
        assertPrinciple2(id, rule);
      } catch (err) {
        violations.push((err as Error).message);
      }
    }

    expect(violations, `Violations:\n${violations.join('\n')}`).toHaveLength(0);
  });

  it('mutation: rule with empty examples.bad causes assertion to fail (anti-tautology)', () => {
    const manifest = loadManifest();
    const [firstId, firstRule] = Object.entries(manifest)[0] as [string, RuleEntry];

    const mutated: RuleEntry = {
      ...firstRule,
      examples: { bad: '   ', good: firstRule.examples.good },
    };

    expect(() => assertPrinciple2(firstId, mutated)).toThrow(/examples\.bad.*absent.*short/);
  });

  it('mutation: rule where bad === good causes assertion to fail (anti-tautology)', () => {
    const manifest = loadManifest();
    const [firstId, firstRule] = Object.entries(manifest)[0] as [string, RuleEntry];

    const mutated: RuleEntry = {
      ...firstRule,
      examples: { bad: firstRule.examples.good, good: firstRule.examples.good },
    };

    expect(() => assertPrinciple2(firstId, mutated)).toThrow(/tautology/);
  });

  it('all synthesized rules in expected-fixture-synth.json have non-trivial paired examples [M2]', () => {
    const fixture = loadSynthFixture();
    expect(fixture.rules.length).toBeGreaterThan(0);
    const violations: string[] = [];
    for (const rule of fixture.rules) {
      try {
        assertPrinciple2(rule.id, rule);
      } catch (err) {
        violations.push((err as Error).message);
      }
    }
    expect(violations, `Violations:\n${violations.join('\n')}`).toHaveLength(0);
  });

  it('every eslint-checked synthesized rule has a non-empty negative-test.input distinct from examples.good [M2]', () => {
    const fixture = loadSynthFixture();
    const violations: string[] = [];
    for (const rule of fixture.rules) {
      if (rule.check.type !== 'eslint') continue;
      const nt = rule['negative-test'];
      if (!nt) {
        violations.push(`${rule.id}: eslint rule has no negative-test`);
        continue;
      }
      if (!nt.input || nt.input.trim().length < MIN_EXAMPLE_LENGTH) {
        violations.push(`${rule.id}: negative-test.input is empty or trivial`);
        continue;
      }
      if (!nt['expect-violation'] || nt['expect-violation'].trim().length === 0) {
        violations.push(`${rule.id}: negative-test.expect-violation is empty`);
        continue;
      }
      if (nt.input.trim() === rule.examples.good.trim()) {
        violations.push(
          `${rule.id}: negative-test.input is identical to examples.good — tautology (input must violate the rule)`,
        );
      }
    }
    expect(violations, `Violations:\n${violations.join('\n')}`).toHaveLength(0);
  });
});
