#!/usr/bin/env tsx
import { readFileSync, writeFileSync, existsSync } from 'node:fs';
import { resolve } from 'node:path';

interface RuleEntry {
  title: string;
  stack: string[];
  'requires-package'?: string | string[];
  'auto-skip-if-missing'?: boolean;
}

type Manifest = Record<string, RuleEntry>;

const PROJECT_ROOT = process.cwd();
const FRAMEWORK_ROOT =
  process.argv[2] || resolve(PROJECT_ROOT, '.ai-factory');

const manifestPath = resolve(FRAMEWORK_ROOT, 'rules-manifest.json');
const manifest: Manifest = JSON.parse(readFileSync(manifestPath, 'utf8'));

const pkgPath = resolve(PROJECT_ROOT, 'package.json');
const pkg = existsSync(pkgPath)
  ? JSON.parse(readFileSync(pkgPath, 'utf8'))
  : { dependencies: {}, devDependencies: {} };
const installed = new Set([
  ...Object.keys(pkg.dependencies ?? {}),
  ...Object.keys(pkg.devDependencies ?? {}),
]);

interface Decision {
  id: string;
  status: 'ENABLED' | 'SKIPPED';
  reason: string;
}

const decisions: Decision[] = [];

for (const [id, rule] of Object.entries(manifest)) {
  let status: Decision['status'] = 'ENABLED';
  let reason = 'applicable';

  if (rule['requires-package'] && rule['auto-skip-if-missing']) {
    const required = Array.isArray(rule['requires-package'])
      ? rule['requires-package']
      : [rule['requires-package']];
    const missing = required.filter((p) => !installed.has(p));
    if (missing.length > 0) {
      status = 'SKIPPED';
      reason = `${missing.join(', ')} not in package.json`;
    }
  }

  decisions.push({ id, status, reason });
}

const md = [
  '# INSTALL-DECISIONS.md',
  '',
  '> Auto-generated by `scripts/detect-applicable-rules.ts`. Re-run when `package.json` changes significantly.',
  '> The AI agent installing this framework should confirm each line below with the user (or auto-confirm if `--yes` was passed).',
  '',
  '| Rule | Title | Status | Reason |',
  '|---|---|---|---|',
  ...decisions.map(
    (d) =>
      `| ${d.id} | ${manifest[d.id].title} | ${d.status} | ${d.reason} |`,
  ),
  '',
].join('\n');

const outPath = resolve(PROJECT_ROOT, 'INSTALL-DECISIONS.md');
writeFileSync(outPath, md);
console.log(`Wrote ${decisions.length} decisions to ${outPath}`);
