/**
 * Principle 2 — Paired negative test for each rule
 *
 * Source: overview.md Layer 4 anti-pattern ("Expected value generated by running the code →
 *         tautology farm") + self-testing-docs.md ("Probe без negative test не считается
 *         реализованным") + ai-traps.md §3 (tautological tests)
 *
 * Manifest field checked: examples.bad (the "negative test" counterpart — shows what violates
 *   the rule). This is the structural proxy for "paired negative test": if examples.bad is
 *   absent or trivially empty, there is no documented violation scenario.
 *
 * Applicability: ALL rules (bad/good examples required by schema for all rule types).
 *
 * Note on deeper paired-negative-test infrastructure (running examples through ESLint):
 *   That requires Phase 5 runtime. Phase 2 covers structural presence only.
 *   See principles-as-tests.md §Known limitations.
 */
import { describe, it, expect } from 'vitest';
import { readFileSync, readdirSync } from 'node:fs';
import { execSync, spawnSync } from 'node:child_process';
import { resolve, dirname } from 'node:path';
import { fileURLToPath } from 'node:url';

const HERE = dirname(fileURLToPath(import.meta.url));
const REPO_ROOT = resolve(HERE, '../../..');
const MANIFEST_PATH = resolve(HERE, '../manifest/rules-manifest.json');
const SYNTH_FIXTURE_PATH = resolve(
  HERE,
  '../synthesizer/expected-fixture-synth.json',
);

// Stage 3C — content-level gate paths
const HOOKS_DIR = resolve(HERE, '../hooks');
const AUDIT_SELF_DIR = resolve(HERE, '../audit-self');
const BASH_MUTATOR = resolve(HERE, '../audit-self/run-bash-mutation.sh');
const HOOK_MARKER_SH = resolve(REPO_ROOT, '.claude/hooks/check-hook-marker.sh');

interface RuleEntry {
  title: string;
  stack: string[];
  check: { type: string; [key: string]: unknown };
  examples: { bad: string; good: string };
  policy?: string;
  'negative-test'?: { input: string[]; 'expect-violation': string; eslintRuleConfig?: unknown };
  [key: string]: unknown;
}

interface SynthesizedRuleEntry extends RuleEntry {
  id: string;
  'negative-test'?: { input: string[]; 'expect-violation': string; eslintRuleConfig?: unknown };
}

interface SynthFixture {
  rules: SynthesizedRuleEntry[];
}

type Manifest = Record<string, RuleEntry>;

function loadManifest(): Manifest {
  return JSON.parse(readFileSync(MANIFEST_PATH, 'utf8')) as Manifest;
}

function loadSynthFixture(): SynthFixture {
  return JSON.parse(readFileSync(SYNTH_FIXTURE_PATH, 'utf8')) as SynthFixture;
}

/** Minimum meaningful content length (not just whitespace or a comment marker) */
const MIN_EXAMPLE_LENGTH = 5;

// ── Stage 3C — content-level paired-negative gate ────────────────────────────

/**
 * Detects test files that have the ❌+✅ paired-negative contract shape.
 * Presence of the "Paired-negative contract:" block or an ❌/PAIRED-NEGATIVE
 * marker counts as the mutation-sanity docstring required by Stage 3C:
 * the block documents what violation was tried and what was expected.
 * (source: packages/core/hooks/check-hook-marker.test.ts:10-15)
 */
const PAIRED_NEGATIVE_RE = /❌|Paired-negative contract|PAIRED-NEGATIVE/;

/**
 * Content-level assertion patterns — at least one must be present in a
 * file with the ❌+✅ shape to pass the Stage 3C gate.
 *
 * Evidence (verified against real hook test files, T3):
 *   - .toBe(N) exit-code assertions: hooks/check-hook-marker.test.ts:69,74,79
 *   - .toMatch( pattern checks:      hooks/end-of-turn-reminder.test.ts (many)
 *   - .toContain( string checks:     hooks/deps-hash-check.test.ts (many)
 *   - expect(r.status):              hooks/deps-hash-check.test.ts:80+
 *   - expect(r.stdout/.stderr):      hooks/end-of-turn-reminder.test.ts (many)
 */
const CONTENT_ASSERTION_RE =
  /\.toBe\(\s*\d+\s*\)|\.toMatch\(|\.toContain\(|\.toThrow\(|expect\([^)]*\.(status|stdout|stderr|code)\b/;

/**
 * Stage 3C content-level gate: a test file with the ❌+✅ paired-negative
 * contract shape MUST have at least one content-level assertion (exit code,
 * stdout, or stderr content) — not merely .toBeDefined() / shape-only.
 *
 * mutation-sanity-checked (write-time):
 *   ❌ file with only .toBeDefined() → throws "content-level assertion" error
 *   ✅ file with .toBe(N) / .toMatch(/ .toContain(/ status|stdout|stderr → no throw
 */
function assertContentLevel(id: string, content: string): void {
  if (!PAIRED_NEGATIVE_RE.test(content)) {
    return; // not a paired-negative test file — out of scope for this gate
  }
  if (!CONTENT_ASSERTION_RE.test(content)) {
    throw new Error(
      `${id}: has ❌/✅ paired-negative contract but no content-level assertion ` +
        '(exit code, stdout, or stderr check). Replace shape-only .toBeDefined() ' +
        'with e.g. expect(r.status).toBe(1) or expect(out).toMatch(/pattern/).',
    );
  }
}

/** Returns true when universalmutator (the Stage 2 B bash mutator) is on PATH. */
function hasUniversalMutator(): boolean {
  try {
    execSync('command -v mutate', { stdio: 'ignore' });
    execSync('command -v analyze_mutants', { stdio: 'ignore' });
    return true;
  } catch {
    return false;
  }
}
const HAS_UM = hasUniversalMutator();

/**
 * Run the Stage 2 B bash-mutation wrapper
 * (packages/core/audit-self/run-bash-mutation.sh).
 * Output format verified against run-bash-mutation.test.ts:91-101 (T16).
 */
function runBashMutator(hookPath: string, testCmd: string, floor = '60') {
  return spawnSync('bash', [BASH_MUTATOR, hookPath, testCmd, floor], {
    encoding: 'utf8',
    cwd: REPO_ROOT,
  });
}

/**
 * Assert liveness corpus constraints for an ESLint rule's negative-test field.
 * Accumulates violations rather than throwing, so the caller can batch all rules.
 *
 * Constraints (parallel to assertPrinciple2's tautology arm):
 *   1. input array is non-empty
 *   2. each entry is non-trivial (≥ MIN_EXAMPLE_LENGTH chars)
 *   3. no entry is identical to examples.good
 *   4. all entries are distinct (no duplicate bypass variants)
 */
function assertNegativeTestLiveness(id: string, rule: RuleEntry, violations: string[]): void {
  const nt = rule['negative-test'];
  if (!nt) return; // no negative-test present — structural absence checked elsewhere
  if (!Array.isArray(nt.input) || nt.input.length === 0) {
    violations.push(`${id}: negative-test.input must be a non-empty array`);
    return;
  }
  for (const inp of nt.input) {
    if (!inp || inp.trim().length < MIN_EXAMPLE_LENGTH) {
      violations.push(`${id}: negative-test.input entry is empty or trivial`);
    }
    if (inp.trim() === rule.examples.good.trim()) {
      violations.push(`${id}: negative-test.input entry is identical to examples.good — tautology`);
    }
  }
  const distinct = new Set(nt.input.map((s) => s.trim()));
  if (distinct.size < nt.input.length) {
    violations.push(`${id}: negative-test.input has duplicate entries — variants must be distinct`);
  }
}

function assertPrinciple2(id: string, rule: RuleEntry): void {
  const bad = rule.examples?.bad;
  const good = rule.examples?.good;

  if (!bad || bad.trim().length < MIN_EXAMPLE_LENGTH) {
    throw new Error(
      `Rule ${id}: examples.bad is absent or too short (< ${MIN_EXAMPLE_LENGTH} chars). ` +
        'A paired negative example is required to document what violates this rule.',
    );
  }

  if (!good || good.trim().length < MIN_EXAMPLE_LENGTH) {
    throw new Error(
      `Rule ${id}: examples.good is absent or too short (< ${MIN_EXAMPLE_LENGTH} chars). ` +
        'A paired positive example is required to document what satisfies this rule.',
    );
  }

  // The bad and good examples must differ — identical examples = tautology
  if (bad.trim() === good.trim()) {
    throw new Error(
      `Rule ${id}: examples.bad and examples.good are identical — this is a tautology. ` +
        'The negative example must show a different (violating) pattern from the positive.',
    );
  }
}

describe(
  'Principle 2 Stage 3C — content-level paired-negative gate (hook test files)',
  () => {
    /**
     * mutation-sanity-checked (write-time):
     *   ❌ file with ❌+✅ shape but only .toBeDefined() → assertContentLevel throws
     *   ✅ file with .toBe(N) exit-code assertion → no throw
     *
     * Paired-negative contract:
     *   ❌ shape-only (only .toBeDefined()) → content-level gate FAILS
     *   ✅ content assertion present → content-level gate PASSES
     */
    it(
      'mutation: file with ❌/✅ shape but only .toBeDefined() fails content gate [M3]',
      () => {
        const shapeOnly = `
/**
 * Paired-negative contract:
 *   ❌ hook missing marker → fails
 *   ✅ hook has marker → passes
 */
it('PAIRED-NEGATIVE: hook with no marker → fails', () => {
  const r = runHook('Write', abs);
  expect(r).toBeDefined();
});`;
        expect(() => assertContentLevel('shape-only.test.ts', shapeOnly)).toThrow(
          /content-level assertion/,
        );
      },
    );

    it(
      'mutation: file with exit-code assertion passes content gate [M3]',
      () => {
        const real = `
/**
 * Paired-negative contract:
 *   ❌ hook missing marker → exit 1
 *   ✅ hook has marker → exit 0
 */
it('PAIRED-NEGATIVE: hook with no marker → exit 1', () => {
  const r = runHook('Write', abs);
  expect(r.status).toBe(1);
});`;
        expect(() => assertContentLevel('real.test.ts', real)).not.toThrow();
      },
    );

    it(
      'all hook/audit-self test files with paired-negative contracts have content-level assertions [M3]',
      () => {
        const violations: string[] = [];
        for (const dir of [HOOKS_DIR, AUDIT_SELF_DIR]) {
          const files = readdirSync(dir).filter((f) => f.endsWith('.test.ts'));
          for (const file of files) {
            const content = readFileSync(resolve(dir, file), 'utf8');
            try {
              assertContentLevel(file, content);
            } catch (err) {
              violations.push((err as Error).message);
            }
          }
        }
        expect(violations, `Violations:\n${violations.join('\n')}`).toHaveLength(0);
      },
    );
  },
);

describe.skipIf(!HAS_UM)(
  'Principle 2 Stage 3C — bash mutation kill-rate gate (local/on-demand, ≥60% floor)',
  () => {
    /**
     * Wires the Stage 2 B bash mutator (universalmutator ADAPT, SSOT #91) to
     * register a kill-rate assertion within principle 02. Skipped in CI (no
     * universalmutator — matches Stryker devDep-only delivery). Run locally:
     *   packages/core/audit-self/run-bash-mutation.sh \
     *     .claude/hooks/check-hook-marker.sh \
     *     "npx vitest run hooks/check-hook-marker.test.ts" 60
     *
     * Output format verified against run-bash-mutation.test.ts:91-101 (T16):
     *   "kill rate: XX%  (killed N / survived M of P)"
     *   "PASS — XX% ≥ YY% floor" or "FAIL — XX% < YY% floor", exit 0/1.
     *
     * mutation-sanity-checked: asserts stdout content (kill rate line) AND
     * exit code — not merely .toBeDefined() (Stage 3C self-application).
     *
     * Paired-negative contract:
     *   ❌ hook test kills < 60% of mutants → wrapper exits 1 (FAIL)
     *   ✅ hook test kills ≥ 60% of mutants → wrapper exits 0 (PASS)
     */
    it(
      'check-hook-marker.sh kills ≥60% of bash mutants (content-strength evidence) [M3-bash]',
      () => {
        const r = runBashMutator(
          HOOK_MARKER_SH,
          'npx vitest run hooks/check-hook-marker.test.ts',
        );
        const out = (r.stdout ?? '') + (r.stderr ?? '');
        expect(out).toMatch(/kill rate: \d+%/);
        expect(r.status).toBe(0); // ≥ 60% floor — content-level assertion on exit code
      },
      // The bash mutator spawns `npx vitest` once per mutant — inherently slow
      // (~9.5s observed on a loaded host). The default 5000ms vitest timeout
      // false-fails this local/on-demand gate (HAS_UM only). Mirrors the Stryker
      // precedent (principle 11 testTimeout 5s→30s); 60s margin covers host load.
      60_000,
    );
  },
);

describe('Principle 2 — Paired negative test (examples.bad + examples.good)', () => {
  it('all rules have non-trivial paired bad/good examples', () => {
    const manifest = loadManifest();
    const violations: string[] = [];

    for (const [id, rule] of Object.entries(manifest)) {
      try {
        assertPrinciple2(id, rule);
      } catch (err) {
        violations.push((err as Error).message);
      }
    }

    expect(violations, `Violations:\n${violations.join('\n')}`).toHaveLength(0);
  });

  it('mutation: rule with empty examples.bad causes assertion to fail (anti-tautology)', () => {
    const manifest = loadManifest();
    const [firstId, firstRule] = Object.entries(manifest)[0] as [string, RuleEntry];

    const mutated: RuleEntry = {
      ...firstRule,
      examples: { bad: '   ', good: firstRule.examples.good },
    };

    expect(() => assertPrinciple2(firstId, mutated)).toThrow(/examples\.bad.*absent.*short/);
  });

  it('mutation: rule where bad === good causes assertion to fail (anti-tautology)', () => {
    const manifest = loadManifest();
    const [firstId, firstRule] = Object.entries(manifest)[0] as [string, RuleEntry];

    const mutated: RuleEntry = {
      ...firstRule,
      examples: { bad: firstRule.examples.good, good: firstRule.examples.good },
    };

    expect(() => assertPrinciple2(firstId, mutated)).toThrow(/tautology/);
  });

  it('all synthesized rules in expected-fixture-synth.json have non-trivial paired examples [M2]', () => {
    const fixture = loadSynthFixture();
    expect(fixture.rules.length).toBeGreaterThan(0);
    const violations: string[] = [];
    for (const rule of fixture.rules) {
      try {
        assertPrinciple2(rule.id, rule);
      } catch (err) {
        violations.push((err as Error).message);
      }
    }
    expect(violations, `Violations:\n${violations.join('\n')}`).toHaveLength(0);
  });

  it('every eslint-checked synthesized rule has a non-empty negative-test.input array with distinct variants [M2]', () => {
    const fixture = loadSynthFixture();
    const violations: string[] = [];
    for (const rule of fixture.rules) {
      if (rule.check.type !== 'eslint') continue;
      const nt = rule['negative-test'];
      if (!nt) {
        violations.push(`${rule.id}: eslint rule has no negative-test`);
        continue;
      }
      if (!Array.isArray(nt.input) || nt.input.length === 0) {
        violations.push(`${rule.id}: negative-test.input must be a non-empty array`);
        continue;
      }
      if (!nt['expect-violation'] || nt['expect-violation'].trim().length === 0) {
        violations.push(`${rule.id}: negative-test.expect-violation is empty`);
        continue;
      }
      for (const inp of nt.input) {
        if (!inp || inp.trim().length < MIN_EXAMPLE_LENGTH) {
          violations.push(`${rule.id}: negative-test.input entry is empty or trivial`);
        }
        if (inp.trim() === rule.examples.good.trim()) {
          violations.push(
            `${rule.id}: negative-test.input entry is identical to examples.good — tautology`,
          );
        }
      }
      const distinct = new Set(nt.input.map((s) => s.trim()));
      if (distinct.size < nt.input.length) {
        violations.push(`${rule.id}: negative-test.input has duplicate entries — variants must be distinct`);
      }
    }
    expect(violations, `Violations:\n${violations.join('\n')}`).toHaveLength(0);
  });
});

describe('Principle 2 — Liveness corpus (manifest ESLint rules)', () => {
  /**
   * Extension of the structural paired-negative check to the manifest layer.
   * For ESLint rules that carry a negative-test field, assert:
   *   1. input array is non-empty (≥1 entry)
   *   2. all entries are distinct (anti-tautology — no duplicate bypass variants)
   *   3. no entry is identical to examples.good (existing paired-negative invariant)
   *
   * mutation-sanity-checked (write-time):
   *   ❌ ESLint rule with duplicate negative-test inputs → "duplicate entries" violation
   *   ✅ ESLint rule with distinct negative-test inputs → no violation
   *
   * Paired-negative contract:
   *   ❌ duplicate inputs in negative-test.input → duplicate-entries error thrown
   *   ✅ distinct inputs, non-trivial → no error
   */
  it('mutation: ESLint rule with duplicate negative-test inputs fails liveness assertion [M4]', () => {
    const dupRule: RuleEntry = {
      title: 'test rule',
      stack: ['ts-server'],
      check: { type: 'eslint', rule: 'test/rule' },
      examples: { bad: 'bad code', good: 'good code' },
      'negative-test': { input: ['bad code', 'bad code'], 'expect-violation': 'test/rule' },
    };
    const violations: string[] = [];
    assertNegativeTestLiveness('TEST', dupRule, violations);
    expect(violations.join('')).toMatch(/duplicate/);
  });

  it('mutation: ESLint rule with distinct negative-test inputs passes liveness assertion [M4]', () => {
    const goodRule: RuleEntry = {
      title: 'test rule',
      stack: ['ts-server'],
      check: { type: 'eslint', rule: 'test/rule' },
      examples: { bad: 'bad code', good: 'good code' },
      'negative-test': { input: ['bad code v1', 'bad code v2'], 'expect-violation': 'test/rule' },
    };
    const violations: string[] = [];
    assertNegativeTestLiveness('TEST', goodRule, violations);
    expect(violations).toHaveLength(0);
  });

  it('all manifest ESLint rules with negative-test have non-empty distinct input arrays [M4]', () => {
    const manifest = loadManifest();
    const violations: string[] = [];
    for (const [id, rule] of Object.entries(manifest)) {
      if (rule.check.type !== 'eslint') continue;
      assertNegativeTestLiveness(id, rule, violations);
    }
    expect(violations, `Violations:\n${violations.join('\n')}`).toHaveLength(0);
  });
});
